name: Tests and lint

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm i
    - name: Unit Tests
      run: npm run test:ci
